services:
  mssql:
    container_name: mssql-2019-container
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "HotelBooking123@"
    hostname: host.docker.internal
    ports:
      - 1400:1433
  app:
    container_name: hotel-booking-container
    image: hotel-booking-image
    ports:
      - 127.0.0.1:8081:8081
    working_dir: /app